### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wlpotter**
testing protected branch functionality

### CODE REVIEW

**Review by baskauf — APPROVED** [review]

**Comment by baskauf** [comment]
OK, apparently a non-administrator can approve changes. Hmmm...

**Comment by baskauf** [comment]
@wlpotter see if you can do the merge now.

**Comment by wlpotter** [comment]
Yes, it looks like I can merge this in myself

**Comment by baskaufs** [comment]
OK @wlpotter, excellent. I was thinking that would be true.

**Pull request merged**
